config/routes.rb
Rails.application.routes.draw do

	resources :players do
		member do
			get 'rest'
			get 'get-modifiers'
			get 'get-skills'
		end

		resources :spells, except: [], controller: :player_spells do
			member do
				get 'use'
			end
		end

		resources :weapons, except: [:show]
		resources :items, except: [:show]

	end

	resources :spells

end

app/models/player_spell.rb
class PlayerSpell < ActiveRecord::Base

	belongs_to :player
	belongs_to :spell

	default_scope { joins(:player, :spell).order(:level, 'spells.name') }

	def use
		unless self.is_cantrip?
			self.available = false
			self.save
		end
	end

	def is_cantrip?
		self.level == 0
	end

end

app/controllers/player_spells_controller.rb
class PlayerSpellsController < ApplicationController

	before_action :set_player_spell, only: [:show, :edit, :update, :destroy, :use]

	# layout 'modal', only: [:show]
	layout 'modal'

	# GET /player_spells
	# GET /player_spells.json
	def index
		@player_spells = PlayerSpell.all
	end

	# GET /player_spells/1
	# GET /player_spells/1.json
	def show
		@attrib_keys = ["desc", "higher_level", "range", "components", "material", "ritual", "duration", "concentration", "casting_time", "level", "school", "class_names", "archetype", "domains", "oaths", "circles", "patrons"]
	end

	def use
		@player_spell.use
		redirect_to [@player_spell.player, {anchor: 'spells'}]
	end

	# GET /player_spells/new
	def new
		@player_spell = PlayerSpell.new(player_id: params[:player_id])
	end

	# GET /player_spells/1/edit
	def edit
	end

	# POST /player_spells
	# POST /player_spells.json
	def create
		@player_spell = PlayerSpell.new(player_spell_params)

		respond_to do |format|
			if @player_spell.save
				format.html { redirect_to [@player_spell.player, {anchor: 'spells'}], notice: 'Player spell was successfully created.' }
				format.json { render :show, status: :created, location: @player_spell }
			else
				format.html { render :new }
				format.json { render json: @player_spell.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /player_spells/1
	# PATCH/PUT /player_spells/1.json
	def update
		respond_to do |format|
			if @player_spell.update(player_spell_params)
				format.html { redirect_to [@player_spell.player, {anchor: 'spells'}], notice: 'Player spell was successfully updated.' }
				format.json { render :show, status: :ok, location: @player_spell }
			else
				format.html { render :edit }
				format.json { render json: @player_spell.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /player_spells/1
	# DELETE /player_spells/1.json
	def destroy
		@player = @player_spell.player
		@player_spell.destroy
		respond_to do |format|
			format.html { redirect_to [@player, {anchor: 'spells'}], notice: 'Player spell was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_player_spell
		@player_spell = PlayerSpell.find_by(player_id: params[:player_id], spell_id: params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def player_spell_params
		params.require(:player_spell).permit!
	end
end

app/helpers/player_spells_helper.rb
module PlayerSpellsHelper

	def spell_level(level)
		if level.to_i < 0
			'Class'
		elsif level.to_i == 0
			'Cantrip'
		else
			"Level #{level}"
		end
	end

	def spell_level_panel_class(level)
		if level.to_i < 0
			'panel-primary'
		elsif level.to_i == 0
			'panel-info'
		else
			'panel-default'
		end
	end

end

app/views/player_spells/_form.html.erb
<%= form_for(@player_spell) do |f| %>

<div class="modal-body">

	<% if @player_spell.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@player_spell.errors.count, "error") %> prohibited this player_spell from being saved:</h2>

		<ul>
			<% @player_spell.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= f.hidden_field :player_id %>

	<div class="form-group">
		<%= f.select :spell_id, Spell.all.map{ |s| [s.name, s.id] }, {include_blank: '-'}, {class: 'form-control input-lg focus-here'} %>
	</div>
	<div class="form-group">
		<%= f.label :level %>
		<%= f.select :level, (1..9).map{ |i| [i,i] }.unshift(['Class', -1], ['Cantrip', 0]), {}, {class: 'form-control'} %>
	</div>

</div>

<footer class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	<%= f.submit nil, class: 'btn btn-primary' %>
</footer>

<% end %>

app/views/player_spells/edit.html.erb
<h1>Editing Player Spell</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_spell %> |
<%= link_to 'Back', player_spells_path %>

app/views/player_spells/index.html.erb
<h3>
	Spells
	<%= link_to raw('<i class="fa fa-plus"></i>'), new_player_spell_path(@player), data: { toggle: :modal, target: '#defaultModal' } %>
</h3>
<div id="levels" class="row">

	<div class="hidden-xs">
		<div class="row">
			<% @player.player_spells.group_by(&:level).each do |level| %>
			<%= render 'player_spells/levels/level', level: level %>
			<% end %>
		</div>
	</div>

	<div class="vidible-xs-block">
		<%= render 'player_spells/levels/carousel' %>
	</div>

</div>

app/views/player_spells/new.html.erb
<% @modal_title = 'Add Spell' %>
<%= render 'form' %>

app/views/player_spells/show.html.erb
<% @modal_title = @player_spell.spell.name %>

<div class="modal-body">
	<table class="table table-striped">
		<tbody>
			<% @attrib_keys.each do |k| %>
			<% if @player_spell.spell.send(k).present? %>
			<tr>
				<th>
					<%= k.titleize %>
				</th>
				<td>
					<%= raw @player_spell.spell.send(k) %>
				</td>
			</tr>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

<footer class="modal-footer">
	<%= link_to 'Edit Spell', edit_spell_path(@player_spell.spell), class: 'btn btn-sm btn-default pull-left' %>
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<%= link_to 'Remove', player_spell_path(@player_spell.player, @player_spell.spell), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
	<%= link_to 'Use', use_player_spell_path(@player_spell.player, @player_spell.spell), class: 'btn btn-primary' if @player_spell.available %>
</footer>