config/routes.rb
Rails.application.routes.draw do

	resources :players do
		member do
			get 'rest'
			get 'get-modifiers'
			get 'get-skills'
		end

		resources :spells, except: [], controller: :player_spells do
			member do
				get 'use'
			end
		end

		resources :weapons, except: [:show]
		resources :items, except: [:show]

	end

	resources :spells

end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
	belongs_to :player
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController

	before_action :set_player, except: []
	before_action :set_weapon, only: [:show, :edit, :update, :destroy]

	layout 'modal'

	# GET /weapons
	# GET /weapons.json
	def index
		@weapons = Weapon.all
	end

	# GET /weapons/1
	# GET /weapons/1.json
	def show
	end

	# GET /weapons/new
	def new
		@weapon = Weapon.new player: @player
	end

	# GET /weapons/1/edit
	def edit
	end

	# POST /weapons
	# POST /weapons.json
	def create
		@weapon = Weapon.new(weapon_params)

		respond_to do |format|
			if @weapon.save
				format.html { redirect_to [@player, {anchor: 'weapons'}], notice: 'Weapon was successfully created.' }
				format.json { render :show, status: :created, location: @weapon }
			else
				format.html { render :new }
				format.json { render json: @weapon.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /weapons/1
	# PATCH/PUT /weapons/1.json
	def update
		respond_to do |format|
			if @weapon.update(weapon_params)
				format.html { redirect_to [@player, {anchor: 'weapons'}], notice: 'Weapon was successfully updated.' }
				format.json { render :show, status: :ok, location: @weapon }
			else
				format.html { render :edit }
				format.json { render json: @weapon.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /weapons/1
	# DELETE /weapons/1.json
	def destroy
		@weapon.destroy
		respond_to do |format|
			format.html { redirect_to [@player, {anchor: 'weapons'}], notice: 'Weapon was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def set_player
		@player = Player.find(params[:player_id])
	end

	def set_weapon
		@weapon = Weapon.find(params[:id])
	end

	def weapon_params
		params.require(:weapon).permit(:name, :attack, :damage, :notes, :player_id)
	end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.erb
<%= form_for [@player, @weapon] do |f| %>

<div class="modal-body">

	<% if @weapon.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

		<ul>
			<% @weapon.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= f.hidden_field :player_id %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control focus-here' %>
	</div>
	<div class="form-group">
		<%= f.label :damage %>
		<%= f.text_field :damage, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :attack, 'Attack Bonus' %>
		<%= f.number_field :attack, class: 'form-control' %>
	</div>

</div>

<footer class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	<%= f.submit nil, class: 'btn btn-primary' %>
</footer>

<% end %>

app/views/weapons/_weapon.html.erb
<%= content_tag_for :tr, weapon, class: 'text-center' do %>

	<td class="text-muted text-left">
		<i class="fa fa-fw fa-arrows-v"></i>
	</td>
	<td>
		<%= link_to weapon.name, edit_player_weapon_path(@player, weapon), data: { toggle: :modal, target: '#defaultModal' } %>
	</td>
	<td>
		<%= weapon.damage %>
	</td>
	<td>
		<%= weapon.attack %>
	</td>
	<td class="text-right">
		<%= link_to raw('<i class="fa fa-fw fa-remove text-warning"></i>'), [@player, weapon], method: :delete, data: { confirm: 'Are you sure?' } %>
	</td>

<% end %>

app/views/weapons/edit.html.erb
<% @modal_title = 'Edit Weapon' %>
<%= render 'form' %>

app/views/weapons/index.html.erb
<% if @player.weapons.any? %>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th></th>
			<th class="text-center">Name</th>
			<th class="text-center">Damage</th>
			<th class="text-center">Atk. Bonus</th>
			<th></th>
		</tr>
	</thead>
	<tbody id="weapons" class="sortable">
		<%= render @player.weapons %>
	</tbody>
</table>

<% else %>

<div class="list-group text-center">
	<%= link_to 'Add a Weapon', new_player_weapon_path(@player), class: 'list-group-item', data: { toggle: :modal, target: '#defaultModal' } %>
</div>

<% end %>

app/views/weapons/new.html.erb
<% @modal_title = 'Add Weapon' %>
<%= render 'form' %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weapon.name %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @weapon.attack %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @weapon.damage %>
</p>

<p>
  <strong>Player:</strong>
  <%= @weapon.player %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>