config/routes.rb
Rails.application.routes.draw do

	resources :players do
		member do
			get 'rest'
			get 'get-modifiers'
			get 'get-skills'
		end

		resources :spells, except: [], controller: :player_spells do
			member do
				get 'use'
			end
		end

		resources :weapons, except: [:show]
		resources :items, except: [:show]

	end

	resources :spells

end

app/models/player.rb
class Player < ActiveRecord::Base

	include PlayerCreation

	has_many :player_spells, dependent: :destroy
	has_many :spells, through: :player_spells

	has_many :weapons, dependent: :destroy
	has_many :items, dependent: :destroy

	validates :name, :race, presence: true
	validates :rank, :xp, :hp, :hp_max, :armor, :initiative, :speed, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :inspiration, :proficiency_bonus, :mod_Strength, :mod_Dexterity, :mod_Constitution, :mod_Intelligence, :mod_Wisdom, :mod_Charisma, numericality: { only_integer: true }

	default_scope { includes(:spells, :weapons, :items) }

	def rest
		self.hp = self.hp_max
		self.player_spells.each{ |s| s.available = true }
		self.save
	end

	def test
		'#'
	end

	ABILITIES.each do |ability|
		# def moded_Strength
		define_method("moded_#{ability}") do
			if is_proficient_in_ability?(ability)
				self.send("mod_#{ability}") + self.proficiency_bonus
			else
				self.send("mod_#{ability}")
			end
		end
	end

	SKILLS.each do |skill|
		# def moded_Acrobatics
		define_method(skill.name) do
			if is_proficient_in_skill?(skill.name)
				self.send("mod_#{skill.modifier}") + self.proficiency_bonus
			else
				self.send("mod_#{skill.modifier}")
			end
		end
	end

	def is_proficient_in_ability?(ability)
		self.send("mod_#{ability}_prof")
	end

	def is_proficient_in_skill?(skill_name)
		self.send("skill_#{skill_name.parameterize.underscore}_prof")
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	before_action :set_player, except: [:index, :new, :create]

	# GET /players
	# GET /players.json
	def index
		@players = Player.all
	end

	# GET /players/1
	# GET /players/1.json
	def show
	end

	def rest
		@player.rest
		redirect_to @player
	end

	def get_modifiers
		render template: 'players/modifiers/index', layout: false
	end

	def get_skills
		render template: 'players/skills/index', layout: false
	end

	# GET /players/new
	def new
		@player = Player.new
	end

	# GET /players/1/edit
	def edit
		@player.player_spells.build
	end

	# POST /players
	# POST /players.json
	def create
		@player = Player.new(player_params)

		respond_to do |format|
			if @player.save
				format.html { redirect_to @player, notice: 'Player was successfully created.' }
				format.json { render :show, status: :created, location: @player }
			else
				format.html { render :new }
				format.json { render json: @player.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /players/1
	# PATCH/PUT /players/1.json
	def update
		respond_to do |format|
			if @player.update(player_params)
				format.html { redirect_to @player, notice: 'Player was successfully updated.' }
				format.json { render :show, status: :ok, location: @player }
			else
				format.html { render :edit }
				format.json { render json: @player.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /players/1
	# DELETE /players/1.json
	def destroy
		@player.destroy
		respond_to do |format|
			format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_player
		@player = Player.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def player_params
		# params.require(:player).permit(:name, :rank, :class_name, :race, :alignment, :xp, player_spells_attributes: [:id, :level, :spell_id, :_destroy])
		params.require(:player).permit!.except(:id, :created_at, :updated_at)
	end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
<% if @player.errors.any? %>
<div id="error_explanation" class="text-danger">
	<h2 class="text-danger"><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

	<ul>
		<% @player.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>

</div>
<% end %>

<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
</div>

<% if @player.new_record? %>
<section id="new-record-attributes">
	<div class="form-group">
		<%= f.label :race %>
		<%= f.select :race, RACES.map(&:name), {include_blank: '-'}, {class: 'form-control'} %>
	</div>

	<div class="form-group">
		<%= f.check_box :use_standard_abilities, checked: true %>
		<%= f.label :use_standard_abilities, 'Use the "Standard Set"' %>
		<a href="#" data-toggle="tooltip" title='The "Standard Set" for abilities is: 15,14,13,12,10,8. Otherwise sum of best 3/4 6-sided die.'>
			<i class="fa fa-question-circle"></i>
		</a>
	</div>
</section>
<% end %>

<div class="form-group">
	<%= f.label :personality %>
	<%= f.text_area :personality, rows: 4, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :ideals %>
	<%= f.text_area :ideals, rows: 4, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :bonds %>
	<%= f.text_area :bonds, rows: 4, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :flaws %>
	<%= f.text_area :flaws, rows: 4, class: 'form-control' %>
</div>

<div class="actions">
	<%= f.submit nil, class: 'btn btn-primary' %>
</div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Player', new_player_path, class: 'btn btn-success pull-right' %>
<%= content_tag :h2, 'Players' %>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Rank</th>
				<th>Class name</th>
				<th>Race</th>
				<th>Alignment</th>
				<th>XP</th>
				<th colspan="2"></th>
			</tr>
		</thead>

		<tbody>
			<% @players.each do |player| %>
			<tr>
				<td><%= link_to player.name, player %></td>
				<td><%= player.rank %></td>
				<td><%= player.class_name %></td>
				<td><%= player.race %></td>
				<td><%= player.alignment %></td>
				<td><%= player.xp %></td>
				<td><%= link_to 'Edit', edit_player_path(player) %></td>
				<td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<div class="player" data-object="player" data-url="<%= player_path(@player) %>">
	<div class="row">
		<div class="col-sm-5 text-center">
			<h3>
				<%= best_in_place @player, :name, inner_class: 'form-control input-sm' %>
				<small>
					<a class="" data-toggle="collapse" href="#additional-player-info" aria-expanded="false" aria-controls="additional-player-info">
						<i class="fa fa-fw fa-info-circle"></i>
					</a>
				</small>
			</h3>
			<p class="btn-group" role="group">
				<%= link_to 'Rest', rest_player_path(@player), class: 'btn btn-sm btn-default' %>
				<%= link_to 'Edit', edit_player_path(@player), class: 'btn btn-sm btn-default' %>
			</p>
		</div>
		<div class="col-sm-7">
			<table class="table table-bordered table-condensed">
				<tbody class="small text-center">
					<tr>
						<td>
							<strong>Class:</strong><br>
							<%= best_in_place @player, :class_name, inner_class: 'form-control input-sm' %>
						</td>
						<td>
							<strong>Level:</strong><br>
							<%= best_in_place @player, :rank, inner_class: 'form-control input-sm' %>
						</td>
						<td>
							<strong>Hit Points:</strong><br>
							<center>
								<%= best_in_place @player, :hp, inner_class: 'form-control input-sm' %>
								/
								<%= best_in_place @player, :hp_max, inner_class: 'form-control input-sm' %>
							</center>
						</td>
					</tr>
					<tr>
						<td>
							<strong>Race:</strong><br>
							<%= best_in_place @player, :race, as: :select, collection: RACES.map{ |r| [r.name, r.name] }, inner_class: 'form-control input-sm' %>
						</td>
						<td>
							<strong>Alignment:</strong><br>
							<%= best_in_place @player, :alignment, inner_class: 'form-control input-sm' %>
						</td>
						<td>
							<strong>Experience Points:</strong><br>
							<%= best_in_place @player, :xp, inner_class: 'form-control input-sm' %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<div class="collapse" id="additional-player-info">
		<div class="well well-sm">
			<dl class="panel-body">
				<dt>Personality</dt>
				<dd><%= @player.personality %></dd>
				<dt>Ideals</dt>
				<dd><%= @player.ideals %></dd>
				<dt>Bonds</dt>
				<dd><%= @player.bonds %></dd>
				<dt>Flaws</dt>
				<dd><%= @player.flaws %></dd>
			</dl>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5 col-md-push-7 col-sm-6 col-sm-push-6">

			<div class="row text-center">
				<div class="col-xs-4">
					<h4 class="thumbnail">
						<%= best_in_place @player, :armor, inner_class: 'form-control input-sm' %><br>
						<small>
							Armor
						</small>
					</h4>
				</div>
				<div class="col-xs-4">
					<h4 class="thumbnail">
						<%= best_in_place @player, :initiative, inner_class: 'form-control input-sm' %><br>
						<small>
							Initiaitve
						</small>
					</h4>
				</div>
				<div class="col-xs-4">
					<h4 class="thumbnail">
						<%= best_in_place @player, :speed, inner_class: 'form-control input-sm' %><br>
						<small>
							Speed
						</small>
					</h4>
				</div>
			</div>
			<div class="panel panel-info">
				<header class="panel-heading">
					<%= link_to raw('<i class="fa fa-plus"></i>'), new_player_weapon_path(@player), class: 'pull-right', data: { toggle: :modal, target: '#defaultModal' } %>
					<h4 class="panel-title text-center">
						Weapons & Attacks
					</h4>
				</header>
				<%= render template: 'weapons/index' %>
			</div>
			<div class="panel panel-info">
				<header class="panel-heading">
					<%= link_to raw('<i class="fa fa-plus"></i>'), new_player_item_path(@player), class: 'pull-right', data: { toggle: :modal, target: '#defaultModal' } %>
					<h4 class="panel-title text-center">
						Inventory
					</h4>
				</header>
				<%= render template: 'items/index' %>
			</div>

		</div>
		<div class="col-md-7 col-md-pull-5 col-sm-6 col-sm-pull-6">

			<div class="row">
				<div class="col-sm-3">

					<div class="row text-center">
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :strength, inner_class: 'form-control input-sm' %><br>
								<small>
									Strength
								</small>
							</h5>
						</div>
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :dexterity, inner_class: 'form-control input-sm' %><br>
								<small>
									Dexterity
								</small>
							</h5>
						</div>
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :constitution, inner_class: 'form-control input-sm' %><br>
								<small>
									Constitution
								</small>
							</h5>
						</div>
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :intelligence, inner_class: 'form-control input-sm' %><br>
								<small>
									Intelligence
								</small>
							</h5>
						</div>
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :wisdom, inner_class: 'form-control input-sm' %><br>
								<small>
									Wisdom
								</small>
							</h5>
						</div>
						<div class="col-xs-4 col-sm-12">
							<h5 class="thumbnail">
								<%= best_in_place @player, :charisma, inner_class: 'form-control input-sm' %><br>
								<small>
									Charisma
								</small>
							</h5>
						</div>
					</div>

				</div>
				<div class="col-sm-9">

					<div class="row">
						<div class="col-md-4">
							<h4 class="thumbnail text-center">
								<%= best_in_place @player, :inspiration, inner_class: 'form-control input-sm' %>
								<br>
								<small>
									Inspiration
								</small>
							</h4>
						</div>
						<div class="col-md-4">
							<h4 class="thumbnail text-center">
								<%= best_in_place @player, :proficiency_bonus, class: 'reload-player', inner_class: 'form-control input-sm' %>
								<br>
								<small>
									Prof. Bonus
								</small>
							</h4>
						</div>
						<div class="col-md-4">
							<h4 class="thumbnail text-center">
								<%#= best_in_place @player, :proficiency_bonus, inner_class: 'form-control input-sm' %>
								#
								<br>
								<small>
									Passive Percep.
								</small>
							</h4>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<div id="modifiers" class="panel panel-default">
								<%= render template: 'players/modifiers/index' %>
							</div>
						</div>
						<div class="col-md-6">
							<div id="skills" class="panel panel-default">
								<%= render template: 'players/skills/index' %>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>

	<section id="spells">
		<%= render template: 'player_spells/index' %>
	</section>

</div>