config/routes.rb
Rails.application.routes.draw do

	resources :players do
		member do
			get 'rest'
			get 'get-modifiers'
			get 'get-skills'
		end

		resources :spells, except: [], controller: :player_spells do
			member do
				get 'use'
			end
		end

		resources :weapons, except: [:show]
		resources :items, except: [:show]

	end

	resources :spells

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :player
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :set_player, except: []
	before_action :set_item, only: [:show, :edit, :update, :destroy]

	layout 'modal'

	# GET /items
	# GET /items.json
	def index
		@items = Item.all
	end

	# GET /items/1
	# GET /items/1.json
	def show
	end

	# GET /items/new
	def new
		@item = Item.new player: @player
	end

	# GET /items/1/edit
	def edit
	end

	# POST /items
	# POST /items.json
	def create
		@item = Item.new(item_params)

		respond_to do |format|
			if @item.save
				format.html { redirect_to [@player, {anchor: 'items'}], notice: 'Item was successfully created.' }
				format.json { render :show, status: :created, location: @item }
			else
				format.html { render :new }
				format.json { render json: @item.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /items/1
	# PATCH/PUT /items/1.json
	def update
		respond_to do |format|
			if @item.update(item_params)
				format.html { redirect_to [@player, {anchor: 'items'}], notice: 'Item was successfully updated.' }
				format.json { render :show, status: :ok, location: @item }
			else
				format.html { render :edit }
				format.json { render json: @item.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /items/1
	# DELETE /items/1.json
	def destroy
		@item.destroy
		respond_to do |format|
			format.html { redirect_to [@player, {anchor: 'items'}], notice: 'Item was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def set_player
		@player = Player.find(params[:player_id])
	end

	def set_item
		@item = Item.find(params[:id])
	end

	def item_params
		params.require(:item).permit(:player_id, :quantity, :name, :notes)
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@player, @item] do |f| %>

<div class="modal-body">

	<% if @item.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

		<ul>
			<% @item.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= f.hidden_field :player_id %>

	<div class="row">
		<div class="col-sm-9">
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>
		</div>
		<div class="col-sm-3">
			<div class="form-group">
				<%= f.label :quantity %>
				<%= f.number_field :quantity, class: 'form-control' %>
			</div>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :notes %>
		<%= f.text_area :notes, class: 'form-control', rows: 5 %>
	</div>

</div>

<footer class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	<%= f.submit nil, class: 'btn btn-primary' %>
</footer>

<% end %>

app/views/items/_item.html.erb
<%= content_tag_for :tr, item, class: 'text-center' do %>

	<td class="text-muted text-left">
		<i class="fa fa-fw fa-arrows-v"></i>
	</td>
	<td>
		<%= link_to item.name, edit_player_item_path(@player, item), data: { toggle: :modal, target: '#defaultModal' } %>
	</td>
	<td>
		<%= item.quantity %>
	</td>
	<td class="text-right">
		<%= link_to raw('<i class="fa fa-fw fa-remove text-warning"></i>'), [@player, item], method: :delete, data: { confirm: 'Are you sure?' } %>
	</td>

<% end %>

app/views/items/edit.html.erb
<% @modal_title = 'Edit Item' %>
<%= render 'form' %>

app/views/items/index.html.erb
<% if @player.items.any? %>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th></th>
			<th class="text-center">Name</th>
			<th class="text-center">Qty.</th>
			<th></th>
		</tr>
	</thead>
	<tbody id="items" class="sortable">
		<%= render @player.items %>
	</tbody>
</table>

<% else %>

<div class="list-group text-center">
	<%= link_to 'Add an Item', new_player_item_path(@player), class: 'list-group-item', data: { toggle: :modal, target: '#defaultModal' } %>
</div>

<% end %>

app/views/items/new.html.erb
<% @modal_title = 'Add Item' %>
<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @item.player %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @item.notes %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>